names = []
print('Enter 5 Names:')
name1 = input()
names.append(name1)
name2 = input()
names.append(name2)
name3 = input()
names.append(name3)
name4 = input()
names.append(name4)
name5 = input()
names.append(name5)
newnames = sorted(names)
print('The names are', names[0], names[1], names[2], names[3], names[4])
#print('The names in alphabetical order are', newnames[0], newnames[1], newnames[2], newnames[3], newnames[4], )
#print('The third name you entered is:', names[2])
replace = int(input('Replace one name. Which one? (1-5): '))
replace = replace - 1
new = input('New name: ')
del(names[replace])
names.insert(replace, new)
print('The names are', names[0], names[1], names[2], names[3], names[4])